drivers/soc: hyp_core_ctl: Include missing cpu.h
- This fixes the following error after dropping tracing from the kernel:
	../drivers/soc/qcom/hyp_core_ctl.c:1127:28: error: use of undeclared identifier 'cpu_subsys'
        ret = sysfs_create_group(&cpu_subsys.dev_root->kobj,
                                  ^

Change-Id: I65f5d2abed2fe619dfa4f6ee3dd073d13f6b54f7